# Generated by Django 3.2.7 on 2021-10-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20211027_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='twoFA',
            new_name='twoFA_enabled',
        ),
    ]
