# Generated by Django 3.2.7 on 2021-10-07 08:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='[A-ZА-Я][a-zа-я\\-]+$')])),
                ('last_name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Please enter a valid last name.', regex='[A-ZА-Я][a-zа-я\\-]+$')])),
                ('middle_name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Please enter a valid middle name.', regex='[A-ZА-Я][a-zа-я\\-]+$')])),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_structures.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_degree', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Please enter a valid scientific degree.', regex='[A-ZА-Я][a-zа-я\\-\\s]+$')])),
                ('position', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Please enter a valid scientific degree.', regex='[A-ZА-Я][a-zа-я\\-\\s]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='user_accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_card_id', models.BigIntegerField(validators=[functools.partial(utils.validators.validate_number_len, *(), **{'digits_number': 8})])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_structures.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='user_accounts.useraccount')),
            ],
        ),
    ]
